http:
  routers:
    traefik:
      rule: "Host(`traefik.docker.local`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.local"
            sans:
              - "*.docker.local"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/etc/certs/local-cert.pem"
        keyFile: "/etc/certs/local-key.pem"

