version: '3.2'

services:
  traefik:
    image: "traefik:latest"
    command:
      - --accesslog
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=frontend
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=admin@tcmi.edu
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --log.level=ERROR
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web,websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.tcmi.edu`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=le
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - le_data:/letsencrypt

  portainer:
    image: portainer/portainer-ee:latest
    command: -H unix:///var/run/docker.sock --templates https://raw.githubusercontent.com/edutcm/edustack/main/templates.json
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./templates.json:/usr/share/nginx/html/templates.json
    networks:
      - frontend
    labels:
      # Frontend
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.tcmi.edu`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=le
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      # Edge
      - traefik.http.routers.edge.rule=Host(`edge.tcmi.edu`)
      - traefik.http.routers.edge.entrypoints=websecure
      - traefik.http.routers.edge.tls=true
      - traefik.http.routers.edge.tls.certresolver=le
      - traefik.http.services.edge.loadbalancer.server.port=8000
      - traefik.http.routers.edge.service=edge

networks:
  frontend:
    external: true
  agent_network:
    external: true

volumes:
  portainer_data:
    driver: local
  le_data:
    driver: local